---
title: "Praise for statistical developers"
subtitle: "Those that write statistical software sit at the intersection of two difficult disciplines. They are heroes."
summary: "Those that write statistical software sit at the intersection of two difficult disciplines. They are heroes."
authors: 
  - admin
categories:
- Opinion
date: '2021-02-18'
lastmod: '2021-02-18T17:11:52Z'
draft: false
featured: no
image:
  caption: 'Photo by [Benjamin Davies on Unsplash](https://unsplash.com/photos/FiZTaNTj2Ak)'
  focal_point: ''
  preview_only: no
---

Statistics is hard.
Computer programming is hard.
To write accurate and reusable statistical software, you have to be good at both.
And if you can do both, people should be high-fiving you in the street and gifting you Iberian hams.


## All hail the statistical developers
How many statisticians in their careers will need to fit a mixed-effects model? Almost all.
How many will try different covariance structures or generalisations for binary and/or count data? Most.
How many could write the code to fit such a model? Barely any. 

I do not mean how many statisticians could use existing tools to fit such a model.
I mean how many statisticians, starting from scratch, facing an empty text file, writing R or C++ or Python or Julia or whatever, would have a cat in hell's chance of producing code to fit a mixed-effects model with all the bells and whistles?
I wouldn't.
The mere idea makes me want to lay down.

Chatting with a colleague, [Nico Kist](https://github.com/nicokist) recently, he floated the idea that researchers need to be careful when they develop tools, because programmers are somehow perceived as less important than other researchers, like coding is the pursuit of those that cannot do proper research.
Desk flesh.
Code monkeys. 
Give them a giant bag of Cheesie Wotsits and stick on a Spiderman DVD and they will leave you alone.

And I agreed with him.
There is career risk, I think, in being seen as a programmer / researcher rather than out-and-out researcher.
Perhaps there is some faulty application of zero-sum logic that diminishes your perceived talents if you also understand [object oriented programming](https://en.wikipedia.org/wiki/Object-oriented_programming).

But this should not be the case!
Nobody has done more to improve R in the last 10 years than Hadley Wickham.
R was, to be blunt, an awkward language to use.
The [tidyverse](https://www.tidyverse.org/) has made modern R an actual joy to behold and something I recommend without qualification to every analyst.

Likewise, [Stan](https://mc-stan.org/) has completely changed the game in statistical modelling.
The broad suite of packages in the Stan ecosystem has shoved us all miles forwards in statistical modelling, model checking, visualisation, model combination, probabilistic decision making, etc.
I was so blown away when I realised the utterly bewildering array of statistical models that could be fit using [brms](https://cran.r-project.org/web/packages/brms/index.html) that I wanted to carry the author, Paul-Christian Bürkner, aloft on a makeshift throne, like C3PO and the Ewoks at the end of Return of the Jedi.

Looking at the R packages I have used in the last month, I have to say to the authors of 
[dplyr](https://cran.r-project.org/package=dplyr), 
[ggplot2](https://cran.r-project.org/package=ggplot2),
[rlang](https://cran.r-project.org/package=rlang),
[R6](https://cran.r-project.org/package=R6),
[httr](https://cran.r-project.org/package=httr),
[magrittr](https://cran.r-project.org/package=magrittr),
[glue](https://cran.r-project.org/package=glue),
[tibble](https://cran.r-project.org/package=tibble),
[purrr](https://cran.r-project.org/package=purrr),
[furrr](https://cran.r-project.org/package=furrr),
[tidyselect](https://cran.r-project.org/package=tidyselect),
[withr](https://cran.r-project.org/package=withr),
[Rcpp](https://cran.r-project.org/package=Rcpp),
[RcppParallel](https://cran.r-project.org/package=RcppParallel),
[rstan](https://cran.r-project.org/package=rstan),
[rstanarm](https://cran.r-project.org/package=rstanarm),
[loo](https://cran.r-project.org/package=loo),
[brms](https://cran.r-project.org/package=brms),
[testthat](https://cran.r-project.org/package=testthat),
[curl](https://cran.r-project.org/package=curl),
[jsonlite](https://cran.r-project.org/package=jsonlite),
[V8](https://cran.r-project.org/package=V8),
[tidybayes](https://cran.r-project.org/package=tidybayes),
[lattice](https://cran.r-project.org/package=lattice),
[here](https://cran.r-project.org/package=here),
[DoseFinding](https://cran.r-project.org/package=DoseFinding),
[patchwork](https://cran.r-project.org/package=patchwork),
[xtable](https://cran.r-project.org/package=xtable),
[gtsummary](https://cran.r-project.org/package=gtsummary),
[lme4](https://cran.r-project.org/package=lme4),
[binom](https://cran.r-project.org/package=binom),
[broom](https://cran.r-project.org/package=broom),
[broom.mixed](https://cran.r-project.org/package=broom.mixed),
[RBesT](https://cran.r-project.org/package=RBesT),
[tidyr](https://cran.r-project.org/package=tidyr),
[forcats](https://cran.r-project.org/package=forcats),
[lubridate](https://cran.r-project.org/package=lubridate),
[readxl](https://cran.r-project.org/package=readxl),
[pwr](https://cran.r-project.org/package=pwr), and
[devtools](https://cran.r-project.org/package=devtools)
that you truly are the best amongst us.
I owe you a ham.

