<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.6.3">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Kristian Brock">

  
  
  
    
  
  <meta name="description" content="Simulation is the popular approach but brute-force enumeration is more accurate and can even be quicker.">

  
  <link rel="alternate" hreflang="en-us" href="https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/">

  


  
  
  
  <meta name="theme-color" content="#4caf50">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157979306-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           document.location = url;
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target);  
  }

  gtag('js', new Date());
  gtag('config', 'UA-157979306-1', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/">

  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@CatchTwentyToo">
  <meta property="twitter:creator" content="@CatchTwentyToo">
  
  <meta property="og:site_name" content="Kristian Brock">
  <meta property="og:url" content="https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/">
  <meta property="og:title" content="Simulation or enumeration with dose-finding designs? | Kristian Brock">
  <meta property="og:description" content="Simulation is the popular approach but brute-force enumeration is more accurate and can even be quicker."><meta property="og:image" content="https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/featured.jpg">
  <meta property="twitter:image" content="https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/featured.jpg"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-04-23T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-05-13T19:57:32&#43;01:00">
  

  


    






  






<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/"
  },
  "headline": "Simulation or enumeration with dose-finding designs?",
  
  "image": [
    "https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/featured.jpg"
  ],
  
  "datePublished": "2020-04-23T00:00:00Z",
  "dateModified": "2020-05-13T19:57:32+01:00",
  
  "author": {
    "@type": "Person",
    "name": "Kristian Brock"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Kristian Brock",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.kristianbrock.com/img/icon-512.png"
    }
  },
  "description": "Simulation is the popular approach but brute-force enumeration is more accurate and can even be quicker."
}
</script>

  

  


  


  





  <title>Simulation or enumeration with dose-finding designs? | Kristian Brock</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  

<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Kristian Brock</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Kristian Brock</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>Home</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/courses/"><span>Teaching</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact Me</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item">
        <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article">

  




















  
  
    
  


<div class="article-container pt-3">
  <h1>Simulation or enumeration with dose-finding designs?</h1>

  
  <p class="page-subtitle">Simulation is the popular approach but brute-force enumeration is more accurate and can even be quicker.</p>
  

  


<div class="article-metadata">

  
  
  
  
  <div>
    



  
  <span><a href="/authors/admin/">Kristian Brock</a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    May 13, 2020
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    15 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/categories/research/">Research</a></span>
  

</div>

  














</div>


<div class="article-header article-container featured-image-wrapper mt-4 mb-4" style="max-width: 720px; max-height: 480px;">
  <div style="position: relative">
    <img src="/post/simulate-vs-enumerate-dose-finding/featured_hu18c6e7d94c99a0b75e62cc3f8662d05a_993262_720x0_resize_q90_lanczos.jpg" alt="" class="featured-image">
    <span class="article-header-caption">Photo by <a href="https://unsplash.com/photos/WBu5YIjtNH4">Mitchell Luo on Unsplash</a></span>
  </div>
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/rmarkdown-libs/viz/viz.js"></script>
<link href="/rmarkdown-libs/DiagrammeR-styles/styles.css" rel="stylesheet" />
<script src="/rmarkdown-libs/grViz-binding/grViz.js"></script>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>If operating performance of a dose-finding clinical trial design is sought, it is practically guaranteed that this will be by computer simulation.
In a dose-finding simulation, a dose is initially selected and toxicity (and perhaps also efficacy) outcomes are sampled according to some assumed true event probabilities to generate data for some imaginary patients.
The model is fit to the data and the subsequent dose recommendation is given to the next group of imaginary patients.
This iterative and adaptive process continues to conduct a virtual trial.
In this manner, many virtual trials are run to inform the trialists of the operating performance of the design.</p>
<p>However, simulating random virtual trials is not the only way to measure operating performance.
<a href="https://elevanth.org/blog/2017/11/28/build-a-better-markov-chain/">Richard McElreath said</a>:</p>
<blockquote>
<p>If there’s a random way to do something, there’s usually a less random way that is both better and requires more thought.</p>
</blockquote>
<p>In dose-finding trials, a less random method is to calculate each trial path using brute force.</p>
</div>
<div id="simple-example" class="section level2">
<h2>Simple example</h2>
<p>I demonstrated dose paths <span class="citation">(Yap et al. 2017; Brock et al. 2017)</span> in a <a href="/post/dose-paths/">recent post</a> using the <code>escalation</code> package.
Let us walk through a simple example to see how dose-paths and simulation can be used to calculate operating characteristics for a dose-finding trial design.</p>
<p>We load the escalation package:</p>
<pre class="r"><code>library(escalation)</code></pre>
<pre><code>## Loading required package: magrittr</code></pre>
<p>For the sake of illustration, let us use:</p>
<ul>
<li>a continual reassessment method (CRM) design</li>
<li>in a three-dose setting</li>
<li>to target a toxicity rate of 25%</li>
<li>with a dose-toxicity skeleton that anticipates the middle dose is the sought dose:</li>
</ul>
<pre class="r"><code>target &lt;- 0.25
skeleton &lt;- dfcrm::getprior(0.1, target = target, nu = 2, nlevel = 3)

model &lt;- get_dfcrm(skeleton = skeleton, target = target) %&gt;% 
        stop_at_n(n = 6)</code></pre>
<p>We told the model above to stop when the total sample size reached six patients.
Obviously, real trials would generally use larger sample sizes, but six patients will be enough for our illustrative example.</p>
<p>Let us start the trial at the second dose and calculate all possible dose paths for two cohorts of three patients:</p>
<pre class="r"><code>paths &lt;- model %&gt;% get_dose_paths(cohort_sizes = rep(3, 2), next_dose = 2)</code></pre>
<p>Viewing the paths makes clear that the decision space is finite and tractable to exact calculation of probabilities:</p>
<pre class="r"><code>graph_paths(paths)</code></pre>
<div id="htmlwidget-1" style="width:720px;height:720px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"diagram":"digraph {\n\ngraph [layout = \"neato\",\n       outputorder = \"edgesfirst\",\n       bgcolor = \"white\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"2\", fontcolor = \"#440154FF\", fillcolor = \"#35B779FF\"] \n  \"2\" [label = \"3\", fontcolor = \"#31688EFF\", fillcolor = \"#FDE725FF\"] \n  \"3\" [label = \"3\", fontcolor = \"#31688EFF\", fillcolor = \"#FDE725FF\"] \n  \"4\" [label = \"2\", fontcolor = \"#440154FF\", fillcolor = \"#35B779FF\"] \n  \"5\" [label = \"2\", fontcolor = \"#440154FF\", fillcolor = \"#35B779FF\"] \n  \"6\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"7\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"8\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"9\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"10\" [label = \"3\", fontcolor = \"#31688EFF\", fillcolor = \"#FDE725FF\"] \n  \"11\" [label = \"2\", fontcolor = \"#440154FF\", fillcolor = \"#35B779FF\"] \n  \"12\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"13\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"14\" [label = \"2\", fontcolor = \"#440154FF\", fillcolor = \"#35B779FF\"] \n  \"15\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"16\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"17\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"18\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"19\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"20\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n  \"21\" [label = \"1\", fontcolor = \"#FDE725FF\", fillcolor = \"#31688EFF\"] \n\"1\"->\"2\" [label = \"NNN\"] \n\"2\"->\"3\" [label = \"NNN\"] \n\"1\"->\"4\" [label = \"NNT\"] \n\"4\"->\"5\" [label = \"NNN\"] \n\"1\"->\"6\" [label = \"NTT\"] \n\"6\"->\"7\" [label = \"NNN\"] \n\"1\"->\"8\" [label = \"TTT\"] \n\"8\"->\"9\" [label = \"NNN\"] \n\"2\"->\"10\" [label = \"NNT\"] \n\"4\"->\"11\" [label = \"NNT\"] \n\"6\"->\"12\" [label = \"NNT\"] \n\"8\"->\"13\" [label = \"NNT\"] \n\"2\"->\"14\" [label = \"NTT\"] \n\"4\"->\"15\" [label = \"NTT\"] \n\"6\"->\"16\" [label = \"NTT\"] \n\"8\"->\"17\" [label = \"NTT\"] \n\"2\"->\"18\" [label = \"TTT\"] \n\"4\"->\"19\" [label = \"TTT\"] \n\"6\"->\"20\" [label = \"TTT\"] \n\"8\"->\"21\" [label = \"TTT\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p>Our first instinct might tell us that there are lots of terminal nodes that recommend dose 1 and relatively few that recommend dose 3.
We might then infer that selecting dose 1 is likely.
In fact, if the true toxicity probabilities at the three doses are (10%, 17%, 25%), we can calculate the exact operating performance:</p>
<pre class="r"><code>probs &lt;- c(0.10, 0.17, 0.25)
cdp &lt;- paths %&gt;% calculate_probabilities(true_prob_tox = probs)
prob_recommend(cdp)</code></pre>
<pre><code>##    NoDose         1         2         3 
## 0.0000000 0.1128170 0.4047377 0.4824453</code></pre>
<p>to learn that there is a 40.5% chance that the second dose will be recommended, and a 48.2% chance that the third dose will be recommended.</p>
<p>The object name <em>cdp</em> stands for <em>crystallised dose paths</em>, my name for paths that have associated exact probabilities.
Simply printing the object to the console:</p>
<pre class="r"><code>cdp</code></pre>
<pre><code>## Number of nodes: 21 
## Number of terminal nodes: 16 
## 
## Number of doses: 3 
## 
## True probability of toxicity:
##    1    2    3 
## 0.10 0.17 0.25 
## 
## Probability of recommendation:
## NoDose      1      2      3 
##  0.000  0.113  0.405  0.482 
## 
## Probability of continuance:
## [1] 0
## 
## Probability of administration:
##      1      2      3 
## 0.0384 0.6757 0.2859 
## 
## Expected sample size:
## [1] 6
## 
## Expected total toxicities:
## [1] 1.141085</code></pre>
<p>confirms the recommendation probabilities and many other statistics.</p>
<p>The more common way to estimate dose-finding design performance is via simulation.
<code>escalation</code> supports simulation too:</p>
<pre class="r"><code>sims100 &lt;- model %&gt;% 
  simulate_trials(num_sims = 100, true_prob_tox = probs, next_dose = 2)

sims1000 &lt;- model %&gt;% 
  simulate_trials(num_sims = 1000, true_prob_tox = probs, next_dose = 2)</code></pre>
<p>These, too, will estimate the probability that each dose will be recommended when the trial is done:</p>
<pre class="r"><code>prob_recommend(sims100)</code></pre>
<pre><code>## NoDose      1      2      3 
##   0.00   0.15   0.40   0.45</code></pre>
<pre class="r"><code>prob_recommend(sims1000)</code></pre>
<pre><code>## NoDose      1      2      3 
##  0.000  0.112  0.420  0.468</code></pre>
<p>However, the inferences from the simulations are subject to Monte Carlo error because we have used a finite number of samples to estimate an unknown probability.
If we collate the inferences from the dose-paths and simulations:</p>
<pre class="r"><code>library(tibble)
library(dplyr)</code></pre>
<pre class="r"><code>trial_inference &lt;- function(x, n) {
  dose_labs &lt;- c(&#39;NoDose&#39;, dose_indices(x))
  tibble(Dose = dose_labs, ProbRecommend = prob_recommend(x), N = n) %&gt;% 
    mutate(
      ProbRecommendSE = sqrt(ProbRecommend * (1 - ProbRecommend) / N),
      ProbRecommendL = ProbRecommend - 2 * ProbRecommendSE,
      ProbRecommendU = ProbRecommend + 2 * ProbRecommendSE
    )
}

inference &lt;- bind_rows(
  trial_inference(cdp, n = Inf) %&gt;% mutate(Method = &#39;Exact&#39;),
  trial_inference(sims100, n = 100) %&gt;% mutate(Method = &#39;Sims (N=100)&#39;),
  trial_inference(sims1000, n = 1000) %&gt;% mutate(Method = &#39;Sims (N=1000)&#39;),
) </code></pre>
<p>we see the extent and effect of that estimation error:</p>
<pre class="r"><code>library(ggplot2)
inference %&gt;% 
  ggplot(aes(x = Dose, y = ProbRecommend, col = Method)) + 
  geom_point(position = position_dodge(width = 0.3)) + 
  geom_errorbar(aes(ymin = ProbRecommendL, ymax = ProbRecommendU), 
                width = 0.1, position = position_dodge(width = 0.3))</code></pre>
<p><img src="/post/simulate-vs-enumerate-dose-finding/index_files/figure-html/unnamed-chunk-11-1.png" width="720" /></p>
<p>As we might anticipate, the simulation method is hopelessly imprecise with <span class="math inline">\(N=100\)</span> iterations.
In contrast the simulations with <span class="math inline">\(N=1000\)</span> iterations are fairly precise.</p>
<p>Each simulated trial required that the dose selection model be fit twice, once at the end of each of the two cohorts.
A simulation study with 1000 iterations thus required 2000 model fits.
We might justifiably conclude that <em>fairly precise</em> is a comparatively bad return on 2000 model invocations when the exact inferences from the dose paths required precisely 21 model fits, one for each of the nodes in the graph above.</p>
<p>Dose paths are more precise than simulations because they are free from the Monte Carlo error that clouds inferences from simulations.
In this toy scenario, the paths method was also vastly more efficient, requiring only a small fraction of the model fits.</p>
<p>However, this contrived example is unlikely to be representative of real trial scenarios, where we would expect much higher sample sizes.
This invites the question, how far can the dose paths method be taken?
When does it become more efficient to run simulations than attempting a brute force calculation?</p>
</div>
<div id="calculating-paths-at-scale" class="section level2">
<h2>Calculating paths at scale</h2>
<p>Contrasting the computational efficiency of dose paths and simulations requires calculating the number of model invocations expected by each.</p>
<p>For simulations, the arithmetic is simple.
Investigating a dose-finding trial of <span class="math inline">\(M\)</span> cohorts in a single scenario using a simulation study with <span class="math inline">\(N\)</span> replicates requires <span class="math inline">\(MN\)</span> model invocations.
For example, a trial of <span class="math inline">\(n=30\)</span> patients evaluated in 10 cohorts requires 10 model invocations, so 1000 simulated replicates requires <span class="math inline">\(10 \times 1000 = 10000\)</span> model fits in total.</p>
<p>In a dose paths analysis, the model must be fit once for each node in the graph.
The number of nodes in a dose paths analysis is slightly more complex to calculate (but only slightly).
Let <span class="math inline">\(k\)</span> be the number of distinct outcomes a single patient may experience.
In a phase I trial using the CRM, each patient may experience toxicity (T) or no toxicity (N), so <span class="math inline">\(k= 2\)</span>.
The number of outcome combinations in a cohort of <span class="math inline">\(m\)</span> patients is</p>
<p><span class="math display">\[ \frac{(m + k - 1)!}{m! (k - 1)!} \]</span>.</p>
<p>For instance, a cohort of three patients has four possible outcomes: NNN, NNT, NTT, or TTT.
The formula above gives <span class="math inline">\((3 + 2 - 1)! / 3! (2 - 1)! = 4\)</span>.</p>
<p>That is the number of outcomes of a single cohort.
The number of nodes at depth <span class="math inline">\(i\)</span> in a graph of dose paths is equal to the number of nodes at depth <span class="math inline">\(i-1\)</span> multiplied by the number of cohort outcomes at depth <span class="math inline">\(i\)</span>.
There is always one node at depth 1 at the centre of the graph.
For a cohort of three in a CRM trial, we saw above that there are four possible outcomes.
Thus, at depth 2, there are 4 nodes and at depth 2 there are 16 nodes, etc.</p>
<p>Naturally, the cohort sizes may be irregular.
In general, the number of nodes at depth <span class="math inline">\(I\)</span> for cohort sizes <span class="math inline">\((m_1, ..., m_I)\)</span> is</p>
<p><span class="math display">\[ \prod_{i=1}^I \frac{(m_i + k - 1)!}{m_i! (k - 1)!} \]</span>.</p>
<p>Fortunately, there is a function in <code>escalation</code> that calculates the number of nodes in a dose paths analysis.
Our simple example with <span class="math inline">\(n=6\)</span> patients conducted in two cohorts of three has:</p>
<pre class="r"><code>num_dose_path_nodes(num_patient_outcomes = 2, cohort_sizes = c(3, 3))</code></pre>
<pre><code>## [1]  1  4 16</code></pre>
<p>nodes at depths, 1, 2, and 3, respectively.
The total number of model invocations is the total number of nodes, which is 21, as required.</p>
<p>We can use the function to calculate the number of nodes in an <span class="math inline">\(n=30\)</span> trial with 10 cohorts of three patients:</p>
<pre class="r"><code>n &lt;- num_dose_path_nodes(num_patient_outcomes = 2, cohort_sizes = rep(3, 10))
n</code></pre>
<pre><code>##  [1]       1       4      16      64     256    1024    4096   16384   65536
## [10]  262144 1048576</code></pre>
<p>The number of nodes increases exponentially in graph depth.
The total number of model fits is:</p>
<pre class="r"><code>sum(n)</code></pre>
<pre><code>## [1] 1398101</code></pre>
<p>1.4m model fits is a substantial computational burden.</p>
<p>Clearly dose number of nodes has increased dramatically as the number of cohorts has increased.
Let’s calculate the number of nodes contained in dose-paths of <span class="math inline">\(M\)</span> cohorts of 3, for increasing values of M:</p>
<pre class="r"><code>cohort_size &lt;- 3
num_cohorts &lt;- c(2, 3, 4, 5, 6, 7, 8, 9, 10) %&gt;% as.integer()

library(purrr)
num_model_fits &lt;- map_int(
  num_cohorts, 
  ~ num_dose_path_nodes(num_patient_outcomes = 2, 
                        cohort_sizes = rep(cohort_size, .x)) %&gt;% sum()
)

num_model_fits</code></pre>
<pre><code>## [1]      21      85     341    1365    5461   21845   87381  349525 1398101</code></pre>
<p>THese numbers are the total number of nodes.
The final value confirms that roughly 1.4m nodes feature in a graph of paths for eight cohorts of 3 patients.
Let’s view those numbers of model invocations alongside the equivalent for simulations with <span class="math inline">\(N=1000\)</span> and <span class="math inline">\(10000\)</span> replicates:</p>
<pre class="r"><code>bind_rows(
  tibble(NumCohorts = num_cohorts,
         NumModelFits = num_model_fits,
         Method = &#39;Paths&#39;),
  tibble(NumCohorts = num_cohorts,
         NumModelFits = 1000 * num_cohorts,
         Method = &#39;Sims (N=1000)&#39;),
  tibble(NumCohorts = num_cohorts,
         NumModelFits = 10000 * num_cohorts,
         Method = &#39;Sims (N=10000)&#39;),
) %&gt;% 
  ggplot(aes(x = NumCohorts, y = NumModelFits, col = Method)) + 
  geom_point() + 
  geom_line() + 
  scale_y_log10() + 
  labs(y = &#39;Number of model fits&#39;, x = &#39;Number of cohorts of 3 patients&#39;,
       title = &#39;Computational burden of dose paths and simulation&#39;)</code></pre>
<p><img src="/post/simulate-vs-enumerate-dose-finding/index_files/figure-html/unnamed-chunk-16-1.png" width="720" /></p>
<p>The <span class="math inline">\(y\)</span>-axis on the plot above is on the log-scale.
We see that the number of model fits in the dose paths analysis increases exponentially in the number of cohorts, as expected.
In contrast, the number of model fits required by simulations increases linearly in the number of cohorts, generally from a much higher base.
The result is that the paths analysis is more computationally efficient than simulations:</p>
<ul>
<li>with <span class="math inline">\(N=1000\)</span> iterations when there are fewer than 6 cohorts of 3;</li>
<li>with <span class="math inline">\(N=10000\)</span> iterations when there are fewer than 8 cohorts of 3.</li>
</ul>
<p>Perhaps we do not plan to use cohorts, intending instead to update the dose recommendation after each patient.
We can calculate the computational burdens in this situation:</p>
<pre class="r"><code>cohort_size &lt;- 1
num_cohorts &lt;- seq(from = 1, to = 30, by = 1)

num_model_fits &lt;- map_int(
  num_cohorts, 
  ~ num_dose_path_nodes(num_patient_outcomes = 2, 
                        cohort_sizes = rep(cohort_size, .x)) %&gt;% sum()
)

bind_rows(
  tibble(NumCohorts = num_cohorts,
         NumModelFits = num_model_fits,
         Method = &#39;Paths&#39;),
  tibble(NumCohorts = num_cohorts,
         NumModelFits = 1000 * num_cohorts,
         Method = &#39;Sims (N=1000)&#39;),
  tibble(NumCohorts = num_cohorts,
         NumModelFits = 10000 * num_cohorts,
         Method = &#39;Sims (N=10000)&#39;),
) %&gt;% 
  ggplot(aes(x = NumCohorts, y = NumModelFits, col = Method)) + 
  geom_point() + 
  geom_line() + 
  scale_y_log10() + 
  labs(y = &#39;Number of model fits&#39;, x = &#39;Number of patients&#39;,
       title = &#39;Computational burden of dose paths and simulation&#39;)</code></pre>
<p><img src="/post/simulate-vs-enumerate-dose-finding/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Again, we see that paths are much more efficient for low sample sizes, but sample sizes in excess of 12 - 16 patients favour simulation.</p>
<p>Assuming that dose-finding trials generally have sample sizes of 20-40 patients, that would seem to suggest that simulations clearly vanquish dose-paths for practical use.
However, there is one last major consideration to understand.</p>
<div id="dose-paths-can-be-recycled" class="section level3">
<h3>Dose paths can be recycled</h3>
<p>The computational burdens are calculated above for <em>a single batch of simulations</em> corresponding to a <em>single set of assumed outcome probabilities</em>.
Generally, simulation studies to justify dose-finding designs use many scenarios.
On the number of scenarios to investigate, <span class="citation">Wheeler et al. (2019)</span> advocate that:</p>
<blockquote>
<p>the simulation study should include:</p>
<ul>
<li>scenarios where each dose is in fact the MTD;</li>
<li>two extreme scenarios, in which the lowest dose is above the MTD and the highest dose is below the MTD;</li>
<li>and any others that clinicians believe are plausible.</li>
</ul>
</blockquote>
<p>where MTD means the <em>maximum tolerable dose</em> or the notional target dose.
Thus, Wheeler <em>et al.</em> advocate at least <span class="math inline">\(J + 2\)</span> scenarios, where <span class="math inline">\(J\)</span> is the number of doses under investigation.
The total computational burden for a simulation study of <span class="math inline">\(S\)</span> scenarios is therefore bounded by <span class="math inline">\(NMS\)</span>.
I say <em>bounded by</em> rather than <em>equal to</em> because some trials may stop early, depending on design.</p>
<p>Simulations are arduous because in each scenario you start from scratch.
In stark contrast, dose-paths are reusable.
Calculating all dose paths is a relatively costly exercise.
But once they have been calculated, <em>crystallising</em> the dose-paths with true outcome probabilities to calculate exact operating performance in a scenario is a relatively cheap computation.
The total computational burden under dose-paths will increase much slower than linearly in <span class="math inline">\(S\)</span>.
Put another way, the time required to produce inference on one scenario is of the same order of magnitude as producing inference on many.
It pays to be thorough and with dose-paths, the incremental work to analyse an extra scenario is small.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>The number of nodes in a graph of dose paths increases exponentially in the number of cohorts.
For 10 cohorts of three patients, approximately 10 times as many model fits are required in dose paths compared to simulations with <span class="math inline">\(N = 10000\)</span> replicates (recall that the <span class="math inline">\(y\)</span>-axes above are logarithmic).
That is, we expect simulations to be computationally cheaper here if fewer than 10 scenarios are investigated.
When the models are evaluated after each patient, dose-paths using <span class="math inline">\(n=30\)</span> patients require more than <span class="math inline">\(10^3 = 1000\)</span> times the number of model fits.
Simulations are clearly preferable here.</p>
<p>However, we know that dose-paths are more precise.
Unlike the simulation method, inferences from dose paths are exact because they are free from Monte Carlo error.</p>
<p>When investigating the operating performance of a clinical trial design, researchers spend computer time to increase certainty.
When deciding whether to perform inference via dose paths or simulation, I propose there are three situations:</p>
<ol style="list-style-type: decimal">
<li>In trials with a small number of cohorts, dose-paths will be both faster and more precise and should naturally be the preferred method for inference.</li>
<li>In trials with a modest number of cohorts and many scenarios to analyse, dose-paths will have a similar total computational burden to simulations.
In these situations, the extra precision of dose-paths will make them preferable.</li>
<li>Finally there will be trials with a high number of cohorts where dose-paths are simply infeasible to calculate. Here, simulations will be preferred.</li>
</ol>
<p>A way to investgate the value of the two methods in practice is, ironically, a simulation study.
This would require plausible assumptions on the number of model fits that should be expected in a trial and how many scenarios would be used to evaluate designs.
That feels like it needs a review of the literature but it will have to wait because today I am out of time.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2>References</h2>
<div id="refs" class="references">
<div id="ref-Brock2017a">
<p>Brock, Kristian, Lucinda Billingham, Mhairi Copland, Shamyla Siddique, Mirjana Sirovica, and Christina Yap. 2017. “Implementing the EffTox Dose-Finding Design in the Matchpoint Trial.” <em>BMC Medical Research Methodology</em> 17 (1): 112. <a href="https://doi.org/10.1186/s12874-017-0381-x">https://doi.org/10.1186/s12874-017-0381-x</a>.</p>
</div>
<div id="ref-wheelerHowDesignDosefinding2019">
<p>Wheeler, Graham M., Adrian P. Mander, Alun Bedding, Kristian Brock, Victoria Cornelius, Andrew P. Grieve, Thomas Jaki, et al. 2019. “How to Design a Dose-Finding Study Using the Continual Reassessment Method.” <em>BMC Medical Research Methodology</em> 19 (1). <a href="https://doi.org/10.1186/s12874-018-0638-z">https://doi.org/10.1186/s12874-018-0638-z</a>.</p>
</div>
<div id="ref-Yap2017">
<p>Yap, Christina, Lucinda J. Billingham, Ying Kuen Cheung, Charlie Craddock, and John O’Quigley. 2017. “Dose Transition Pathways: The Missing Link Between Complex Dose-Finding Designs and Simple Decision-Making.” <em>Clinical Cancer Research</em> 23 (24): 7440–7. <a href="https://doi.org/10.1158/1078-0432.CCR-17-0582">https://doi.org/10.1158/1078-0432.CCR-17-0582</a>.</p>
</div>
</div>
</div>

    </div>

    





<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/escalation/">escalation</a>
  
  <a class="badge badge-light" href="/tags/r/">R</a>
  
  <a class="badge badge-light" href="/tags/dosefinding/">DoseFinding</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/&amp;text=Simulation%20or%20enumeration%20with%20dose-finding%20designs?" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/&amp;t=Simulation%20or%20enumeration%20with%20dose-finding%20designs?" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Simulation%20or%20enumeration%20with%20dose-finding%20designs?&amp;body=https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/&amp;title=Simulation%20or%20enumeration%20with%20dose-finding%20designs?" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Simulation%20or%20enumeration%20with%20dose-finding%20designs?%20https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=https://www.kristianbrock.com/post/simulate-vs-enumerate-dose-finding/&amp;title=Simulation%20or%20enumeration%20with%20dose-finding%20designs?" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  
  
    
  
  






  
  
  
    
  
  
  <div class="media author-card content-widget-hr">
    
      <img class="portrait mr-3" src="https://s.gravatar.com/avatar/ba2fdaa5d7c978ce64a39a93043d05ca?s=200')" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="https://www.kristianbrock.com/">Kristian Brock</a></h5>
      <h6 class="card-subtitle">Statistical Consultant</h6>
      <p class="card-text">I am a clinical trial methodology statistician that likes to use Bayesian statistics.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/#contact" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/CatchTwentyToo" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.co.uk/citations?user=zoh03M4AAAAJ&amp;hl=en" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/brockk/" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>









  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/dose-paths/">Dose-paths in the escalation package</a></li>
      
      <li><a href="/post/introducing-escalation/">Introducing escalation</a></li>
      
      <li><a href="/project/escalation/">The escalation package</a></li>
      
      <li><a href="/post/crm-simulations-checklist/">CRM Simulation Checklist</a></li>
      
      <li><a href="/publication/crm-tutorial/">How to design a dose-finding study using the continual reassessment method</a></li>
      
    </ul>
  </div>
  



  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.3/mermaid.min.js" integrity="" crossorigin="anonymous" title="mermaid"></script>
      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.600a2e440c16093e23e26e90951c4d4b.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
